* Prima parte dell'esercitazione

In questa lezione vediamo gli esercizi relativi al controllo in retroazione sull'uscita

** Retroazione algebrica
vediamo prima il caso di una retroazine algebrica sull'uscita, quindi dovemo fare il
guadagno in feedback e il guadagno in feed forward

prima troavre polinomio caratteristico e funzione di trasferimento

visto che è un sistema di ordine 3 da già l'aggiogata

*** Polinomio caratteristico e funzione di trasferimento

I calcoli sono gli stessi ma ho un sistema di ordine maggiore, evviva, sticazzi

trovo il polinomio caratteristico, questo è $s^3 -1$, le radici di sto polinomio sono le
radici cubiche complesse dell'unità, vertici di un triangolo equilatero sul cerchio
unitario

con questo polinomio caratteristico e l'aggiogata e altra roba poi vado a trovarmi la
funzione di trasferimento del sistema

vediamo per quali valori di \alpha ci sono semplificazioni nella funzione di
trasferimento, la difficoltà è principalmente saper ragionare su polinomii parametrici e
vedere per quali valori ci sono semplificazioni in cosi tipo la funzione di trasferimento

per completare lo studio della funzione di trasferimento devo vedere anche [...]

*** Per quali \alpha il problema è ben posto

Il problema di controllo è ben posto se e solamente se il polinomio \phi _h(s), che si
calcola come rapporto tra polinomio caratteristico e denominatore di G(s), è un polinomio
asintoticamente stabile

abbiamo visto nella parte prima che per \alpha \neq -1 allora abbiamo G(s) messo bene,
altrimenti ho un autovalore in 1 nascosto, se ho un autovalore instabile nascosto allora
ho un problema di controllo mal posto, perchè non posso stabilizzare il sistema

per \alpha \neq -1 abbiamo \phi _h(s) = 1, senza autovalori instabili, quindi il problema
di controllo è ben posto

le prime due domande dell'esercizio sono domande di studio preliminari

** Lascia stare sti parametri

mettiamo \alpha = 1

*** vediamo per quali valori di K abbiamo stabilitas et limitata outputitas

una cosa che conviene mettere in un formulario è come sono messi i polinomii
caratteristici e varie funzioni a seconda della legge di controllo

per fare questa cosa vediamo il polimiomio caratteristico in ciclo chiuso
trovata questa abbiamo $a(s)$ e $b(s)$, troviamo \phi *(s), bello bello
al variare di K vediamo la stabilità di sto polinomio

\phi *(s) è un polinomio di 3^{\circle} grado, quindi per studiare la stabilità facciamo
routh-hourbiz (o come cazzo si scrive)

visto che il guadagno in feedback è un parametro la difficoltà qui resta localizzata al
fatto di dover lavorare con polinomii parametrici

facciamo routh e applichiamo la condizione necessaria e sufficiente

stabile \iff tutti gli elementi della prima colonna hanno lo stesso segno
quindi \iff K > 0 \and 4K-1 > 0 \and \frac{4K^2 - 4K + 1}{K} > 0

quidni questi,

suppongo di avere K > 0, il rapporto potrebbe essere positivo se entrambi num e den sono >
0 o sono entrambi < 0, ma qui sappiamo che il denominatore (K) deve essere positivo,
quindi bla bla bla quindi tolgo il denominatore perchè tanto..., quindi bla bla bla blero

risolviamo il sistema, e amen.

quindi va fatto uno studio parametrico sulla base del guadagno in feedback K.

*** Progettare, se possiblite K e H per avere inseguimento perfetto et al

perndiamo la retroazione sull'uscita,
\[ u = -Ky ^ Hy^{\circle} \]
vogliamo K e H in modo da avere inseguimento perfetto e stabilità asintotica

vogliamo stabilità asintotica, visto prima, credo

e vogliamo $G* _{y^{\circle}y} (0)$ = 1, quindi troviamo $G* _{y^{\circle}y} (0)$ in
funzione di H e troviamo H giusto

\[ G* _{y^{\circle}y} (s) = \frac{b(s)}{a(s) + Kb(s)} H \]

abbiamo tutti gli ingredienti apparte H (K sarà un parametro, sticazzi), mettiamo che
$Puttanaio \rvert _{k=0} = 1$, vediamo l'H che lo soddisfa, e fatto, avremo una H in
funzione di K che mi da inseguimento perfetto e belli belli.

*** Oh shit

Adesso abbiamo un riferimento non più costante ma sinusoidale, bisogna applicare il
/teorema della risposta in frequenza/

applichiamo questo /teorema della risposta in frequenza/
Nota bene che a quanto pare non sai fare l'escape di parentesi graffe in latex, vattelo a
rivedere, stronzo.

\[ y_f^Y_0(t) = 5(Re \{G* _{y^{\circle}y} (j\omega _0)\} \sin(\omega _0(t))
+ Im\{G* _{y^{\circle}y} (j\omega _0)\} \cos(\omega _0(t))) 1(t) \]

(o qualcosa del genere)

la frequenza del riferimento costante è unitaria, quindi avremo la funzione di
trasferimento per j\omega _0 = j\omega, la trovi e tanti saluti

(l'esame lo passate anche se il conto coi numeri complessi non finisce bene, magari non
prenderete 30 ma l'importante è impostarlo)

quindi prendiamo la parte reale e la parte immaginaria della risposta in frequenza
($G*_{y^{\circle}y}$) e ci troviamo il regime permanente del sistema

applico il teorema della risposta in frequenza e ci trovo...
a meno di errori di calcolo, ma il procedimento è questo


* Seconda parte dell'esericitazoine

Ora vediamo il caso in cui il controllo è dato da sistema dinamico, qui non abbiamo il prefiltro
in questo schema a blocci non abbiamo H_f, quindi un solo grado di libertà

*** vogliamo progettare $K(s)$ in modo da avere stabilità asintotica in ciclo chiuso

sappiamo che K(s) = \frac{p(s)}{q(s)} con p(s) e q(s) entrambi polinomii di grado n_k, con
a(s) monico

sappiamo che per poter funzionare dobbiamo avere n_k \geq grado a(s) - 1, in questo caso
\geq 2-1 = 1 \to \geq 1

non complichiamoci la vita e mettiamo n_k = 1

troviamo \phi*(s) = \phi _h(s) a*(s)

NB: visto che il processo da controllare è espresso in termine di funzione di
trasferimento si suppone che \phi _h(s) faccia 1

\phi*(s) = a*(s) = roba

abbiamo un polinomio parametrico di 3^{\circle} grado, vogliamo garantire la stabilità
asintotica, non chiede una forma generale, posso semplicemente eguagliare il polinomio
parametrico a un polinomio di mia scelta, routh hourbiz richiederebbe calcoli eterni

è una scelta libera, quindi prendiamo una scelta semplice

*** Progettare un controllore con azione integrale

per introdurre azione integrale nel controllore è necessario avere un polo in 0 (ricorda
PID)
vogliamo sta cosa integrale per inseguimento perfetto di riferimenti costanti e reiezione
perfetta di disturbi costanti

nel denominatore il termine noto deve essere nullo, in modo che il denominatore abbia un
polo in 0, abbiamo un coefficiente in meno, quindi mi serve un grado in più per avere
abbastanza gradi di libertà per poter fare il progetto, quindi passiamo da n_k \geq
grado(0)-1 a n_k > grado a(s)

qui dobbiamo determinare 4 parametri, invece che 3 parametri, tolto 1 col vincolo, messi 2
col grado extra

abbiamo sempre una scelta libera, quindi facciamo \phi*(s) in una forma semplice,
facciamo (s+1)^4 si eguaglia, fatto, ecco che parametri applicare, bello bello
sistematico.

la procedura è esattamente la stessa di prima, abbiamo solo vincolato il denominatore ad
avere un coefficiente fisso, avevamo più parametri quindi i conti erano un po' più noisi,
ma la procedura è del tutto sistematica, basta solo non perdersi in cose inutili come
vedere in modo generico come fare coi paramteri con routh hourbiz o che vuoi, sticazzi
eguaglia stammerda a un polinomio a scelta, tot = tat = amen, prendi 21 e levati dal
cazzo.

*** Hai un errore fisso e un coso di inseguimento

il regime permanente complessivo è dato dalla somma dei due regimi permanenti in risposta
ai due ingressi, per il principio della sovrapposizione degli effetti, sarà pari al regime
permanente di ingresso + il regime permanente di disturbo
\[ y^{RP}(t) = y^{Y_0}(t) + y^D(t) \]

si ricordi bla bla bla del teorema della risposta in frequenza, visto che sono gradini la
frequenza fa 0 o che cazzo era quindi non dobbiamo fare formuloni con seni e coseni e
co'cazzi

mi sono perso con gravità significativa e non potrò seguire in modo soddisfacente il resto
di che cazzo dice per sto punto

mi sa che era l'ultimo punto di oggi, bella merda

quindi mi posso calcolare queste funzioni di trasferimento in ciclo chiuso, sopra ho
questo, sotto ho quest'altro, figaro su, figaro giù, figaro di trasferimento in ciclo
chiuso

l'azione integrale viene cosata per...

NB: in realtà potevo anche non fare i calcoli perchè sapevo già che un controllore con
azione integrale garantisce queste propritetà, quelle chieste dalla traccia, che erano
roba, credo.

detto questo ti trovi i regimi permanenti, trovi che bla bla bla il mio errore a regime è
pari a 0, abbiamo un disturbo costante ma il suo effetto viene completamente reiettato, se
questo disturbo non fosse stato constante avrei dovuto usare bla bla bla risposta in
frequenza o qualcosa ma non verrà annullato completamente.

* Conclusione

con questo ab

ci sarà una prima parte di esercizi
per analisi, per controllo

ci saranno progetti di regolatori o roba simili

dopo gli esercizi ci sarà una parte orale in cui chiederà più o meno tutto, dalla parte di
modellistica alla parte di sistemi di controllo

sistemi in equazioni di stato, ingresso uscita, o funzione di trasferimento

bisogna saper passare da rappresentazione ingresso uscita a roba di trasferimento

l'esame riguarderà in sostanaza solo la parte fatta a lezione, la roba nelle slide non
fatta a lezione non sarà nell'esame

l'esame come da regolamento è in presenza, se siete a firenze e state bene venite a fare
l'esamen in presenza, se siete fuori regione o positivi al nuovo covid-19 allora mi sa che
farete a distanza



